import type { Command, EnvVar, ProjectContext, TechStack } from '../types.js';

function renderTechStack(tech: TechStack): string[] {
  const lines: string[] = [];
  lines.push('## Tech Stack');
  lines.push('');
  if (tech.languages.length > 0) {
    lines.push(`- **Languages:** ${tech.languages.join(', ')}`);
  }
  if (tech.frameworks.length > 0) {
    lines.push(`- **Frameworks:** ${tech.frameworks.join(', ')}`);
  }
  if (tech.runtime) {
    lines.push(`- **Runtime:** ${tech.runtime}`);
  }
  if (tech.packageManager) {
    lines.push(`- **Package manager:** ${tech.packageManager}`);
  }
  if (tech.typeChecker) {
    lines.push(`- **Type checker:** ${tech.typeChecker}`);
  }
  if (tech.testFramework) {
    lines.push(`- **Testing:** ${tech.testFramework}`);
  }
  if (tech.linter) {
    lines.push(`- **Linter:** ${tech.linter}`);
  }
  lines.push('');
  return lines;
}

function renderCommands(commands: Command[]): string[] {
  const lines: string[] = ['## Commands', ''];
  if (commands.length === 0) {
    lines.push('_No commands detected._');
    lines.push('');
    return lines;
  }
  lines.push('| Name | Source | Command | Description |');
  lines.push('| --- | --- | --- | --- |');
  for (const cmd of commands) {
    const name = cmd.name.replace(/\|/g, '\\|');
    const command = cmd.command.replace(/\|/g, '\\|');
    const desc = cmd.description.replace(/\|/g, '\\|');
    lines.push(`| \`${name}\` | ${cmd.source} | \`${command}\` | ${desc} |`);
  }
  lines.push('');
  return lines;
}

function renderEnvironment(env: EnvVar[]): string[] {
  const lines: string[] = ['## Environment', ''];
  if (env.length === 0) {
    lines.push('_No environment variables detected. Add a `.env.example` file to declare them._');
    lines.push('');
    return lines;
  }
  lines.push('| Variable | Required | Default | Description |');
  lines.push('| --- | --- | --- | --- |');
  for (const e of env) {
    const required = e.required ? 'yes' : 'no';
    const def = e.defaultValue ? `\`${e.defaultValue.replace(/\|/g, '\\|')}\`` : '—';
    const comment = e.comment ? e.comment.replace(/\|/g, '\\|') : '—';
    lines.push(`| \`${e.name}\` | ${required} | ${def} | ${comment} |`);
  }
  lines.push('');
  return lines;
}

function renderConventions(conventions: ProjectContext['conventions']): string[] {
  const lines: string[] = ['## Conventions', ''];
  if (conventions.length === 0) {
    lines.push('_No conventions detected._');
    lines.push('');
    return lines;
  }
  for (const c of conventions) {
    lines.push(`- **${c.name}** — ${c.description}${c.evidence ? ` _(${c.evidence})_` : ''}`);
  }
  lines.push('');
  return lines;
}

function renderStructure(structure: ProjectContext['structure']): string[] {
  const lines: string[] = ['## Project Structure', ''];
  lines.push(`- **Files:** ${structure.files.length}`);
  lines.push(`- **Directories:** ${structure.directories.length}`);
  if (structure.keyFiles.length > 0) {
    lines.push(`- **Key files:** ${structure.keyFiles.map((f) => `\`${f}\``).join(', ')}`);
  }
  lines.push('');
  lines.push('```');
  lines.push(structure.tree);
  lines.push('```');
  lines.push('');
  return lines;
}

function renderArchitecture(arch: ProjectContext['architecture']): string[] {
  const lines: string[] = ['## Architecture', ''];
  if (arch.entryPoints.length > 0) {
    lines.push('### Entry Points');
    for (const e of arch.entryPoints) {
      lines.push(`- \`${e}\``);
    }
    lines.push('');
  }
  if (arch.keyModules.length > 0) {
    lines.push('### Key Modules');
    for (const m of arch.keyModules) {
      lines.push(`- \`${m}\``);
    }
    lines.push('');
  }
  if (arch.dataFlow) {
    lines.push('### Data Flow');
    lines.push('');
    lines.push(arch.dataFlow);
    lines.push('');
  }
  return lines;
}

export function renderMarkdown(ctx: ProjectContext): string {
  const lines: string[] = [];
  lines.push(`# ${ctx.projectName}`);
  lines.push('');
  lines.push('> Generated by [ctx](https://github.com/smarthomeo/ctx-cli) on ' + ctx.generatedAt);
  lines.push('');
  lines.push('## Project Overview');
  lines.push('');
  lines.push(ctx.overview || '_No overview available. Add a `README.md` to provide one._');
  lines.push('');
  lines.push(...renderTechStack(ctx.techStack));
  lines.push(...renderStructure(ctx.structure));
  lines.push(...renderConventions(ctx.conventions));
  lines.push(...renderEnvironment(ctx.environment));
  lines.push(...renderCommands(ctx.commands));
  lines.push(...renderArchitecture(ctx.architecture));
  return lines.join('\n');
}

export function buildContextFromMap(map: Partial<ProjectContext>): ProjectContext {
  return {
    projectName: map.projectName ?? 'project',
    overview: map.overview ?? '',
    techStack: map.techStack ?? { languages: [], frameworks: [] },
    structure: map.structure ?? { tree: '', files: [], directories: [], keyFiles: [] },
    conventions: map.conventions ?? [],
    environment: map.environment ?? [],
    commands: map.commands ?? [],
    architecture: map.architecture ?? { entryPoints: [], keyModules: [], dataFlow: '' },
    generatedAt: map.generatedAt ?? new Date().toISOString(),
    rootPath: map.rootPath ?? '',
  };
}
