import { describe, test, expect } from 'vitest';
import { renderMarkdown, buildContextFromMap } from '../../src/generators/markdown.js';
import type { ProjectContext } from '../../src/types.js';

function makeContext(overrides: Partial<ProjectContext> = {}): ProjectContext {
  return {
    projectName: 'demo',
    overview: 'A demo project used in tests.',
    techStack: {
      languages: ['TypeScript'],
      frameworks: ['Express'],
      packageManager: 'npm',
      testFramework: 'Vitest',
      linter: 'ESLint',
      runtime: 'Node.js',
      typeChecker: 'TypeScript',
    },
    structure: {
      tree: 'demo\n├── package.json\n├── src\n│   └── index.ts\n',
      files: ['package.json', 'src/index.ts'],
      directories: ['src'],
      keyFiles: ['package.json'],
    },
    conventions: [{ name: '2-space indent', description: 'Code uses 2 spaces' }],
    environment: [{ name: 'PORT', defaultValue: '3000', required: false }],
    commands: [{ name: 'dev', description: 'Start dev', source: 'package.json', command: 'tsx' }],
    architecture: { entryPoints: ['src/index.ts'], keyModules: ['package.json'], dataFlow: 'flow' },
    generatedAt: '2024-01-01T00:00:00.000Z',
    rootPath: '/tmp/demo',
    ...overrides,
  };
}

describe('renderMarkdown', () => {
  test('includes a top-level title with the project name', () => {
    const md = renderMarkdown(makeContext());
    expect(md).toMatch(/^# demo\b/);
  });

  test('includes the generation timestamp in a blockquote', () => {
    const md = renderMarkdown(makeContext());
    expect(md).toContain('Generated by [ctx]');
    expect(md).toContain('2024-01-01');
  });

  test('renders the project overview section', () => {
    const md = renderMarkdown(makeContext());
    expect(md).toContain('## Project Overview');
    expect(md).toContain('A demo project used in tests.');
  });

  test('renders the tech stack section with all detected attributes', () => {
    const md = renderMarkdown(makeContext());
    expect(md).toContain('## Tech Stack');
    expect(md).toContain('TypeScript');
    expect(md).toContain('Express');
    expect(md).toContain('Node.js');
    expect(md).toContain('npm');
    expect(md).toContain('Vitest');
    expect(md).toContain('ESLint');
  });

  test('renders the project structure section with tree', () => {
    const md = renderMarkdown(makeContext());
    expect(md).toContain('## Project Structure');
    expect(md).toContain('demo');
    expect(md).toContain('package.json');
  });

  test('renders the conventions section', () => {
    const md = renderMarkdown(makeContext());
    expect(md).toContain('## Conventions');
    expect(md).toContain('2-space indent');
  });

  test('renders the environment section as a table', () => {
    const md = renderMarkdown(makeContext());
    expect(md).toContain('## Environment');
    expect(md).toContain('| Variable | Required | Default | Description |');
    expect(md).toContain('`PORT`');
  });

  test('renders the commands section as a table', () => {
    const md = renderMarkdown(makeContext());
    expect(md).toContain('## Commands');
    expect(md).toContain('| Name | Source | Command | Description |');
    expect(md).toContain('`dev`');
  });

  test('renders the architecture section with entries, modules and data flow', () => {
    const md = renderMarkdown(makeContext());
    expect(md).toContain('## Architecture');
    expect(md).toContain('### Entry Points');
    expect(md).toContain('`src/index.ts`');
    expect(md).toContain('### Key Modules');
    expect(md).toContain('### Data Flow');
    expect(md).toContain('flow');
  });

  test('falls back to a placeholder when overview is empty', () => {
    const md = renderMarkdown(makeContext({ overview: '' }));
    expect(md).toContain('_No overview available.');
  });

  test('emits a friendly placeholder for empty conventions', () => {
    const md = renderMarkdown(makeContext({ conventions: [] }));
    expect(md).toContain('_No conventions detected._');
  });

  test('emits a friendly placeholder for empty environment', () => {
    const md = renderMarkdown(makeContext({ environment: [] }));
    expect(md).toContain('_No environment variables detected.');
  });

  test('emits a friendly placeholder for empty commands', () => {
    const md = renderMarkdown(makeContext({ commands: [] }));
    expect(md).toContain('_No commands detected._');
  });

  test('escapes pipe characters in command values', () => {
    const md = renderMarkdown(
      makeContext({
        commands: [{ name: 'pipe', description: 'has |', source: 'package.json', command: 'a|b' }],
      }),
    );
    expect(md).toContain('a\\|b');
  });

  test('renders all section headings in expected order', () => {
    const md = renderMarkdown(makeContext());
    const headings = [
      '## Project Overview',
      '## Tech Stack',
      '## Project Structure',
      '## Conventions',
      '## Environment',
      '## Commands',
      '## Architecture',
    ];
    let cursor = 0;
    for (const h of headings) {
      const idx = md.indexOf(h, cursor);
      expect(idx).toBeGreaterThanOrEqual(0);
      cursor = idx + h.length;
    }
  });
});

describe('buildContextFromMap', () => {
  test('fills in defaults for missing fields', () => {
    const partial = buildContextFromMap({ projectName: 'mini' });
    expect(partial.projectName).toBe('mini');
    expect(partial.techStack).toEqual({ languages: [], frameworks: [] });
    expect(partial.structure).toEqual({ tree: '', files: [], directories: [], keyFiles: [] });
    expect(partial.conventions).toEqual([]);
    expect(partial.environment).toEqual([]);
    expect(partial.commands).toEqual([]);
    expect(partial.architecture).toEqual({ entryPoints: [], keyModules: [], dataFlow: '' });
    expect(partial.rootPath).toBe('');
    expect(typeof partial.generatedAt).toBe('string');
  });

  test('preserves supplied values', () => {
    const ctx = buildContextFromMap({
      projectName: 'kept',
      overview: 'kept overview',
      techStack: { languages: ['Go'], frameworks: ['Gin'] },
    });
    expect(ctx.projectName).toBe('kept');
    expect(ctx.overview).toBe('kept overview');
    expect(ctx.techStack.languages).toEqual(['Go']);
  });
});
